INSERT INTO lands(name, iso_code) VALUES("Afghanistan", "AFG");
INSERT INTO lands(name, iso_code) VALUES("Albania", "ALB");
INSERT INTO lands(name, iso_code) VALUES("Algeria", "DZA");
INSERT INTO lands(name, iso_code) VALUES("American Samoa", "ASM");
INSERT INTO lands(name, iso_code) VALUES("Andorra", "AND");
INSERT INTO lands(name, iso_code) VALUES("Angola", "AGO");
INSERT INTO lands(name, iso_code) VALUES("Anguilla", "AIA");
INSERT INTO lands(name, iso_code) VALUES("Antigua And Barbuda", "ATG");
INSERT INTO lands(name, iso_code) VALUES("Argentina", "ARG");
INSERT INTO lands(name, iso_code) VALUES("Armenia", "ARG");
INSERT INTO lands(name, iso_code) VALUES("Aruba", "ABW");
INSERT INTO lands(name, iso_code) VALUES("Australia", "AUS");
INSERT INTO lands(name, iso_code) VALUES("Austria", "AUT");
INSERT INTO lands(name, iso_code) VALUES("Azerbaijan", "AZE");
INSERT INTO lands(name, iso_code) VALUES("Bahamas, "BS");
INSERT INTO lands(name, iso_code) VALUES("Bahrain", "BHR");
INSERT INTO lands(name, iso_code) VALUES("Bangladesh", "BGD");
INSERT INTO lands(name, iso_code) VALUES("Barbados", "BRB");
INSERT INTO lands(name, iso_code) VALUES("Belarus", "BLR");
INSERT INTO lands(name, iso_code) VALUES("Belgium", "BEL");
INSERT INTO lands(name, iso_code) VALUES("Belize", "BLZ");
INSERT INTO lands(name, iso_code) VALUES("Benin", "BEN");
INSERT INTO lands(name, iso_code) VALUES("Bermuda", "BMU");
INSERT INTO lands(name, iso_code) VALUES("Bhutan", "BTN");
INSERT INTO lands(name, iso_code) VALUES("Bolivia", "BOL");
INSERT INTO lands(name, iso_code) VALUES("Bosnia And Herzegovina", "BIH");
INSERT INTO lands(name, iso_code) VALUES("Botswana", "BWA");
INSERT INTO lands(name, iso_code) VALUES("Brazil", "BRA");
INSERT INTO lands(name, iso_code) VALUES("Brunei", "BRN");
INSERT INTO lands(name, iso_code) VALUES("Bulgaria", "BGR");
INSERT INTO lands(name, iso_code) VALUES("Burkina Faso", "BFA");
INSERT INTO lands(name, iso_code) VALUES("Burundi", "BDI");
INSERT INTO lands(name, iso_code) VALUES("Cabo Verde", "CPV");
INSERT INTO lands(name, iso_code) VALUES("Cambodia", "KHM");
INSERT INTO lands(name, iso_code) VALUES("Cameroon", "CMR");
INSERT INTO lands(name, iso_code) VALUES("Canada", "CAN");
INSERT INTO lands(name, iso_code) VALUES("Cayman Islands", "CYM");
INSERT INTO lands(name, iso_code) VALUES("Central African Republic", "CAF");
INSERT INTO lands(name, iso_code) VALUES("Chad", "TCD");
INSERT INTO lands(name, iso_code) VALUES("Chile", "CHL");
INSERT INTO lands(name, iso_code) VALUES("China", "CHN");
INSERT INTO lands(name, iso_code) VALUES("Christmas Island", "CXR");
INSERT INTO lands(name, iso_code) VALUES("Colombia", "COL");
INSERT INTO lands(name, iso_code) VALUES("Comoros", "COM");
INSERT INTO lands(name, iso_code) VALUES("Congo (Brazzaville)", "COG");
INSERT INTO lands(name, iso_code) VALUES("Congo (Kinshasa)", "COD");
INSERT INTO lands(name, iso_code) VALUES("Cook Islands", "COK");
INSERT INTO lands(name, iso_code) VALUES("Costa Rica", "CRI");
INSERT INTO lands(name, iso_code) VALUES("Côte D’Ivoire", "CIV");
INSERT INTO lands(name, iso_code) VALUES("Croatia", "HRV");
INSERT INTO lands(name, iso_code) VALUES("Cuba", "CUB");
INSERT INTO lands(name, iso_code) VALUES("Curaçao", "CUW");
INSERT INTO lands(name, iso_code) VALUES("Cyprus", "CYP");
INSERT INTO lands(name, iso_code) VALUES("Czechia", "CZE");
INSERT INTO lands(name, iso_code) VALUES("Denmark", "DNK");
INSERT INTO lands(name, iso_code) VALUES("Djibouti", "DJI");
INSERT INTO lands(name, iso_code) VALUES("Dominica", "DMA");
INSERT INTO lands(name, iso_code) VALUES("Dominican Republic", "DOM");
INSERT INTO lands(name, iso_code) VALUES("Ecuador", "ECU");
INSERT INTO lands(name, iso_code) VALUES("Egypt", "EGY");
INSERT INTO lands(name, iso_code) VALUES("El Salvador", "SLV");
INSERT INTO lands(name, iso_code) VALUES("Equatorial Guinea", "GNQ");
INSERT INTO lands(name, iso_code) VALUES("Eritrea", "ERI");
INSERT INTO lands(name, iso_code) VALUES("Estonia", "EST");
INSERT INTO lands(name, iso_code) VALUES("Ethiopia", "ETH");
INSERT INTO lands(name, iso_code) VALUES("Falkland Islands (Islas Malvinas)", "FLK");
INSERT INTO lands(name, iso_code) VALUES("Faroe Islands", "FRO");
INSERT INTO lands(name, iso_code) VALUES("Fiji", "FJI");
INSERT INTO lands(name, iso_code) VALUES("Finland", "FIN");
INSERT INTO lands(name, iso_code) VALUES("France", "FRA");
INSERT INTO lands(name, iso_code) VALUES("French Guiana", "GUF");
INSERT INTO lands(name, iso_code) VALUES("French Polynesia", "PYF");
INSERT INTO lands(name, iso_code) VALUES("Gabon", "GAB");
INSERT INTO lands(name, iso_code) VALUES("Gambia, "GM");
INSERT INTO lands(name, iso_code) VALUES("Gaza Strip", "XGZ");
INSERT INTO lands(name, iso_code) VALUES("Georgia", "GEO");
INSERT INTO lands(name, iso_code) VALUES("Germany", "DEU");
INSERT INTO lands(name, iso_code) VALUES("Ghana", "GHA");
INSERT INTO lands(name, iso_code) VALUES("Gibraltar", "GIB");
INSERT INTO lands(name, iso_code) VALUES("Greece", "GRC");
INSERT INTO lands(name, iso_code) VALUES("Greenland", "GRL");
INSERT INTO lands(name, iso_code) VALUES("Grenada", "GRD");
INSERT INTO lands(name, iso_code) VALUES("Guadeloupe", "GLP");
INSERT INTO lands(name, iso_code) VALUES("Guam", "GUM");
INSERT INTO lands(name, iso_code) VALUES("Guatemala", "GTM");
INSERT INTO lands(name, iso_code) VALUES("Guinea-Bissau", "GNB");
INSERT INTO lands(name, iso_code) VALUES("Guinea", "GIN");
INSERT INTO lands(name, iso_code) VALUES("Guyana", "GUY");
INSERT INTO lands(name, iso_code) VALUES("Haiti", "HTI");
INSERT INTO lands(name, iso_code) VALUES("Honduras", "HND");
INSERT INTO lands(name, iso_code) VALUES("Hong Kong", "HKG");
INSERT INTO lands(name, iso_code) VALUES("Hungary", "HUN");
INSERT INTO lands(name, iso_code) VALUES("Iceland", "ISL");
INSERT INTO lands(name, iso_code) VALUES("India", "IND");
INSERT INTO lands(name, iso_code) VALUES("Indonesia", "IDN");
INSERT INTO lands(name, iso_code) VALUES("Iran", "IRN");
INSERT INTO lands(name, iso_code) VALUES("Iraq", "IRQ");
INSERT INTO lands(name, iso_code) VALUES("Ireland", "IRL");
INSERT INTO lands(name, iso_code) VALUES("Isle Of Man", "IMN");
INSERT INTO lands(name, iso_code) VALUES("Israel", "ISR");
INSERT INTO lands(name, iso_code) VALUES("Italy", "ITA");
INSERT INTO lands(name, iso_code) VALUES("Jamaica", "JAM");
INSERT INTO lands(name, iso_code) VALUES("Japan", "JPN");
INSERT INTO lands(name, iso_code) VALUES("Jersey", "JEY");
INSERT INTO lands(name, iso_code) VALUES("Jordan", "JOR");
INSERT INTO lands(name, iso_code) VALUES("Kazakhstan", "KAZ");
INSERT INTO lands(name, iso_code) VALUES("Kenya", "KEN");
INSERT INTO lands(name, iso_code) VALUES("Kiribati", "KIR");
INSERT INTO lands(name, iso_code) VALUES("Korea, "KP");
INSERT INTO lands(name, iso_code) VALUES("Korea, "KR");
INSERT INTO lands(name, iso_code) VALUES("Kosovo", "XKS");
INSERT INTO lands(name, iso_code) VALUES("Kuwait", "KWT");
INSERT INTO lands(name, iso_code) VALUES("Kyrgyzstan", "KGZ");
INSERT INTO lands(name, iso_code) VALUES("Laos", "LAO");
INSERT INTO lands(name, iso_code) VALUES("Latvia", "LVA");
INSERT INTO lands(name, iso_code) VALUES("Lebanon", "LBN");
INSERT INTO lands(name, iso_code) VALUES("Lesotho", "LSO");
INSERT INTO lands(name, iso_code) VALUES("Liberia", "LBR");
INSERT INTO lands(name, iso_code) VALUES("Libya", "LBY");
INSERT INTO lands(name, iso_code) VALUES("Liechtenstein", "LIE");
INSERT INTO lands(name, iso_code) VALUES("Lithuania", "LTU");
INSERT INTO lands(name, iso_code) VALUES("Luxembourg", "LUX");
INSERT INTO lands(name, iso_code) VALUES("Macau", "MAC");
INSERT INTO lands(name, iso_code) VALUES("Macedonia", "MKD");
INSERT INTO lands(name, iso_code) VALUES("Madagascar", "MDG");
INSERT INTO lands(name, iso_code) VALUES("Malawi", "MWI");
INSERT INTO lands(name, iso_code) VALUES("Malaysia", "MYS");
INSERT INTO lands(name, iso_code) VALUES("Maldives", "MDV");
INSERT INTO lands(name, iso_code) VALUES("Mali", "MLI");
INSERT INTO lands(name, iso_code) VALUES("Malta", "MLT");
INSERT INTO lands(name, iso_code) VALUES("Marshall Islands", "MHL");
INSERT INTO lands(name, iso_code) VALUES("Martinique", "MTQ");
INSERT INTO lands(name, iso_code) VALUES("Mauritania", "MRT");
INSERT INTO lands(name, iso_code) VALUES("Mauritius", "MUS");
INSERT INTO lands(name, iso_code) VALUES("Mayotte", "MYT");
INSERT INTO lands(name, iso_code) VALUES("Mexico", "MEX");
INSERT INTO lands(name, iso_code) VALUES("Micronesia, "FM");
INSERT INTO lands(name, iso_code) VALUES("Moldova", "MDA");
INSERT INTO lands(name, iso_code) VALUES("Monaco", "MCO");
INSERT INTO lands(name, iso_code) VALUES("Mongolia", "MNG");
INSERT INTO lands(name, iso_code) VALUES("Montenegro", "MNE");
INSERT INTO lands(name, iso_code) VALUES("Morocco", "MAR");
INSERT INTO lands(name, iso_code) VALUES("Mozambique", "MOZ");
INSERT INTO lands(name, iso_code) VALUES("Myanmar", "MMR");
INSERT INTO lands(name, iso_code) VALUES("Namibia", "NAM");
INSERT INTO lands(name, iso_code) VALUES("Nepal", "NPL");
INSERT INTO lands(name, iso_code) VALUES("Netherlands", "NLD");
INSERT INTO lands(name, iso_code) VALUES("New Caledonia", "NCL");
INSERT INTO lands(name, iso_code) VALUES("New Zealand", "NZL");
INSERT INTO lands(name, iso_code) VALUES("Nicaragua", "NIC");
INSERT INTO lands(name, iso_code) VALUES("Nigeria", "NGA");
INSERT INTO lands(name, iso_code) VALUES("Niger", "NER");
INSERT INTO lands(name, iso_code) VALUES("Niue", "NIU");
INSERT INTO lands(name, iso_code) VALUES("Norfolk Island", "NFK");
INSERT INTO lands(name, iso_code) VALUES("Northern Mariana Islands", "MNP");
INSERT INTO lands(name, iso_code) VALUES("Norway", "NOR");
INSERT INTO lands(name, iso_code) VALUES("Oman", "OMN");
INSERT INTO lands(name, iso_code) VALUES("Pakistan", "PAK");
INSERT INTO lands(name, iso_code) VALUES("Palau", "PLW");
INSERT INTO lands(name, iso_code) VALUES("Panama", "PAN");
INSERT INTO lands(name, iso_code) VALUES("Papua New Guinea", "PNG");
INSERT INTO lands(name, iso_code) VALUES("Paraguay", "PRY");
INSERT INTO lands(name, iso_code) VALUES("Peru", "PER");
INSERT INTO lands(name, iso_code) VALUES("Philippines", "PHL");
INSERT INTO lands(name, iso_code) VALUES("Pitcairn Islands", "PCN");
INSERT INTO lands(name, iso_code) VALUES("Poland", "POL");
INSERT INTO lands(name, iso_code) VALUES("Portugal", "PRT");
INSERT INTO lands(name, iso_code) VALUES("Puerto Rico", "PRI");
INSERT INTO lands(name, iso_code) VALUES("Qatar", "QAT");
INSERT INTO lands(name, iso_code) VALUES("Reunion", "REU");
INSERT INTO lands(name, iso_code) VALUES("Romania", "ROU");
INSERT INTO lands(name, iso_code) VALUES("Russia", "RUS");
INSERT INTO lands(name, iso_code) VALUES("Rwanda", "RWA");
INSERT INTO lands(name, iso_code) VALUES("Saint Barthelemy", "BLM");
INSERT INTO lands(name, iso_code) VALUES("Saint Helena,  And Tristan Da Cunha");
INSERT INTO lands(name, iso_code) VALUES("Saint Kitts And Nevis", "KNA");
INSERT INTO lands(name, iso_code) VALUES("Saint Lucia", "LCA");
INSERT INTO lands(name, iso_code) VALUES("Saint Martin", "MAF");
INSERT INTO lands(name, iso_code) VALUES("Saint Pierre And Miquelon", "SPM");
INSERT INTO lands(name, iso_code) VALUES("Saint Vincent And The Grenadines", "VCT");
INSERT INTO lands(name, iso_code) VALUES("Samoa", "WSM");
INSERT INTO lands(name, iso_code) VALUES("San Marino", "SMR");
INSERT INTO lands(name, iso_code) VALUES("Sao Tome And Principe", "STP");
INSERT INTO lands(name, iso_code) VALUES("Saudi Arabia", "SAU");
INSERT INTO lands(name, iso_code) VALUES("Senegal", "SEN");
INSERT INTO lands(name, iso_code) VALUES("Serbia", "SRB");
INSERT INTO lands(name, iso_code) VALUES("Seychelles", "SYC");
INSERT INTO lands(name, iso_code) VALUES("Sierra Leone", "SLE");
INSERT INTO lands(name, iso_code) VALUES("Singapore", "SGP");
INSERT INTO lands(name, iso_code) VALUES("Sint Maarten", "SXM");
INSERT INTO lands(name, iso_code) VALUES("Slovakia", "SVK");
INSERT INTO lands(name, iso_code) VALUES("Slovenia", "SVN");
INSERT INTO lands(name, iso_code) VALUES("Solomon Islands", "SLB");
INSERT INTO lands(name, iso_code) VALUES("Somalia", "SOM");
INSERT INTO lands(name, iso_code) VALUES("South Africa", "ZAF");
INSERT INTO lands(name, iso_code) VALUES("South Georgia And South Sandwich Islands", "SGS");
INSERT INTO lands(name, iso_code) VALUES("South Sudan", "SSD");
INSERT INTO lands(name, iso_code) VALUES("Spain", "ESP");
INSERT INTO lands(name, iso_code) VALUES("Sri Lanka", "LKA");
INSERT INTO lands(name, iso_code) VALUES("Sudan", "SDN");
INSERT INTO lands(name, iso_code) VALUES("Suriname", "SUR");
INSERT INTO lands(name, iso_code) VALUES("Svalbard", "XSV");
INSERT INTO lands(name, iso_code) VALUES("Swaziland", "SWZ");
INSERT INTO lands(name, iso_code) VALUES("Sweden", "SWE");
INSERT INTO lands(name, iso_code) VALUES("Switzerland", "CHE");
INSERT INTO lands(name, iso_code) VALUES("Syria", "SYR");
INSERT INTO lands(name, iso_code) VALUES("Taiwan", "TWN");
INSERT INTO lands(name, iso_code) VALUES("Tajikistan", "TJK");
INSERT INTO lands(name, iso_code) VALUES("Tanzania", "TZA");
INSERT INTO lands(name, iso_code) VALUES("Thailand", "THA");
INSERT INTO lands(name, iso_code) VALUES("Timor-Leste", "TLS");
INSERT INTO lands(name, iso_code) VALUES("Togo", "TGO");
INSERT INTO lands(name, iso_code) VALUES("Tonga", "TON");
INSERT INTO lands(name, iso_code) VALUES("Trinidad And Tobago", "TTO");
INSERT INTO lands(name, iso_code) VALUES("Tunisia", "TUN");
INSERT INTO lands(name, iso_code) VALUES("Turkey", "TUR");
INSERT INTO lands(name, iso_code) VALUES("Turkmenistan", "TKM");
INSERT INTO lands(name, iso_code) VALUES("Turks And Caicos Islands", "TCA");
INSERT INTO lands(name, iso_code) VALUES("Tuvalu", "TUV");
INSERT INTO lands(name, iso_code) VALUES("Uganda", "UGA");
INSERT INTO lands(name, iso_code) VALUES("Ukraine", "UKR");
INSERT INTO lands(name, iso_code) VALUES("United Arab Emirates", "ARE");
INSERT INTO lands(name, iso_code) VALUES("United Kingdom", "GBR");
INSERT INTO lands(name, iso_code) VALUES("United States", "USA");
INSERT INTO lands(name, iso_code) VALUES("Uruguay", "URY");
INSERT INTO lands(name, iso_code) VALUES("Uzbekistan", "UZB");
INSERT INTO lands(name, iso_code) VALUES("Vanuatu", "VUT");
INSERT INTO lands(name, iso_code) VALUES("Vatican City", "VAT");
INSERT INTO lands(name, iso_code) VALUES("Venezuela", "VEN");
INSERT INTO lands(name, iso_code) VALUES("Vietnam", "VNM");
INSERT INTO lands(name, iso_code) VALUES("Virgin Islands, "VG");
INSERT INTO lands(name, iso_code) VALUES("Wallis And Futuna", "WLF");
INSERT INTO lands(name, iso_code) VALUES("West Bank", "XWB");
INSERT INTO lands(name, iso_code) VALUES("Western Sahara", "ESH");
INSERT INTO lands(name, iso_code) VALUES("Yemen", "YEM");
INSERT INTO lands(name, iso_code) VALUES("Zambia", "ZMB");
INSERT INTO lands(name, iso_code) VALUES("Zimbabwe", "ZWE");
