INSERT INTO lands(id, iso_code, name) values (1, 'JPN', 'Japan');
INSERT INTO lands(id, iso_code, name) values (2, 'IDN', 'Indonesia');
INSERT INTO lands(id, iso_code, name) values (3, 'IND', 'India');
INSERT INTO lands(id, iso_code, name) values (4, 'PHL', 'Philippines');
INSERT INTO lands(id, iso_code, name) values (5, 'CHN', 'China');
INSERT INTO lands(id, iso_code, name) values (6, 'BRA', 'Brazil');
INSERT INTO lands(id, iso_code, name) values (7, 'KOR', 'Korea, South');
INSERT INTO lands(id, iso_code, name) values (8, 'MEX', 'Mexico');
INSERT INTO lands(id, iso_code, name) values (9, 'EGY', 'Egypt');
INSERT INTO lands(id, iso_code, name) values (10, 'RUS', 'Russia');
INSERT INTO lands(id, iso_code, name) values (11, 'THA', 'Thailand');
INSERT INTO lands(id, iso_code, name) values (12, 'ARG', 'Argentina');
INSERT INTO lands(id, iso_code, name) values (13, 'BGD', 'Bangladesh');
INSERT INTO lands(id, iso_code, name) values (14, 'NGA', 'Nigeria');
INSERT INTO lands(id, iso_code, name) values (15, 'TUR', 'Turkey');
INSERT INTO lands(id, iso_code, name) values (16, 'PAK', 'Pakistan');
INSERT INTO lands(id, iso_code, name) values (17, 'IRN', 'Iran');
INSERT INTO lands(id, iso_code, name) values (18, 'COD', 'Congo (Kinshasa)');
INSERT INTO lands(id, iso_code, name) values (19, 'VNM', 'Vietnam');
INSERT INTO lands(id, iso_code, name) values (20, 'FRA', 'France');
INSERT INTO lands(id, iso_code, name) values (21, 'GBR', 'United Kingdom');
INSERT INTO lands(id, iso_code, name) values (22, 'PER', 'Peru');
INSERT INTO lands(id, iso_code, name) values (23, 'COL', 'Colombia');
INSERT INTO lands(id, iso_code, name) values (24, 'AGO', 'Angola');
INSERT INTO lands(id, iso_code, name) values (25, 'MYS', 'Malaysia');
INSERT INTO lands(id, iso_code, name) values (26, 'HKG', 'Hong Kong');
INSERT INTO lands(id, iso_code, name) values (27, 'SDN', 'Sudan');
INSERT INTO lands(id, iso_code, name) values (28, 'CHL', 'Chile');
INSERT INTO lands(id, iso_code, name) values (29, 'SAU', 'Saudi Arabia');
INSERT INTO lands(id, iso_code, name) values (30, 'TZA', 'Tanzania');
INSERT INTO lands(id, iso_code, name) values (31, 'ESP', 'Spain');
INSERT INTO lands(id, iso_code, name) values (32, 'IRQ', 'Iraq');
INSERT INTO lands(id, iso_code, name) values (33, 'SGP', 'Singapore');
INSERT INTO lands(id, iso_code, name) values (34, 'KEN', 'Kenya');
INSERT INTO lands(id, iso_code, name) values (35, 'MMR', 'Myanmar');
INSERT INTO lands(id, iso_code, name) values (36, 'CAN', 'Canada');
INSERT INTO lands(id, iso_code, name) values (37, 'AUS', 'Australia');
INSERT INTO lands(id, iso_code, name) values (38, 'CIV', 'Côte D’Ivoire');
INSERT INTO lands(id, iso_code, name) values (39, 'ZAF', 'South Africa');
INSERT INTO lands(id, iso_code, name) values (40, 'MAR', 'Morocco');
INSERT INTO lands(id, iso_code, name) values (41, 'JOR', 'Jordan');
INSERT INTO lands(id, iso_code, name) values (42, 'AFG', 'Afghanistan');
INSERT INTO lands(id, iso_code, name) values (43, 'DEU', 'Germany');
INSERT INTO lands(id, iso_code, name) values (44, 'DZA', 'Algeria');
INSERT INTO lands(id, iso_code, name) values (45, 'BOL', 'Bolivia');
INSERT INTO lands(id, iso_code, name) values (46, 'ETH', 'Ethiopia');
INSERT INTO lands(id, iso_code, name) values (47, 'KWT', 'Kuwait');
INSERT INTO lands(id, iso_code, name) values (48, 'UKR', 'Ukraine');
INSERT INTO lands(id, iso_code, name) values (49, 'YEM', 'Yemen');
INSERT INTO lands(id, iso_code, name) values (50, 'ITA', 'Italy');
INSERT INTO lands(id, iso_code, name) values (51, 'PRK', 'Korea, North');
INSERT INTO lands(id, iso_code, name) values (52, 'TWN', 'Taiwan');
INSERT INTO lands(id, iso_code, name) values (53, 'ECU', 'Ecuador');
INSERT INTO lands(id, iso_code, name) values (54, 'MDG', 'Madagascar');
INSERT INTO lands(id, iso_code, name) values (55, 'DOM', 'Dominican Republic');
INSERT INTO lands(id, iso_code, name) values (56, 'ARE', 'United Arab Emirates');
INSERT INTO lands(id, iso_code, name) values (57, 'GTM', 'Guatemala');
INSERT INTO lands(id, iso_code, name) values (58, 'CMR', 'Cameroon');
INSERT INTO lands(id, iso_code, name) values (59, 'UZB', 'Uzbekistan');
INSERT INTO lands(id, iso_code, name) values (60, 'GHA', 'Ghana');
INSERT INTO lands(id, iso_code, name) values (61, 'AZE', 'Azerbaijan');
INSERT INTO lands(id, iso_code, name) values (62, 'ZWE', 'Zimbabwe');
INSERT INTO lands(id, iso_code, name) values (63, 'CUB', 'Cuba');
INSERT INTO lands(id, iso_code, name) values (64, 'KHM', 'Cambodia');
INSERT INTO lands(id, iso_code, name) values (65, 'SOM', 'Somalia');
INSERT INTO lands(id, iso_code, name) values (66, 'MLI', 'Mali');
INSERT INTO lands(id, iso_code, name) values (67, 'BLR', 'Belarus');
INSERT INTO lands(id, iso_code, name) values (68, 'VEN', 'Venezuela');
INSERT INTO lands(id, iso_code, name) values (69, 'SYR', 'Syria');
INSERT INTO lands(id, iso_code, name) values (70, 'KAZ', 'Kazakhstan');
INSERT INTO lands(id, iso_code, name) values (71, 'AUT', 'Austria');
INSERT INTO lands(id, iso_code, name) values (72, 'MWI', 'Malawi');
INSERT INTO lands(id, iso_code, name) values (73, 'ROU', 'Romania');
INSERT INTO lands(id, iso_code, name) values (74, 'PRY', 'Paraguay');
INSERT INTO lands(id, iso_code, name) values (75, 'COG', 'Congo (Brazzaville)');
INSERT INTO lands(id, iso_code, name) values (76, 'POL', 'Poland');
INSERT INTO lands(id, iso_code, name) values (77, 'BEL', 'Belgium');
INSERT INTO lands(id, iso_code, name) values (78, 'HUN', 'Hungary');
INSERT INTO lands(id, iso_code, name) values (79, 'ZMB', 'Zambia');
INSERT INTO lands(id, iso_code, name) values (80, 'GIN', 'Guinea');
INSERT INTO lands(id, iso_code, name) values (81, 'UGA', 'Uganda');
INSERT INTO lands(id, iso_code, name) values (82, 'BFA', 'Burkina Faso');
INSERT INTO lands(id, iso_code, name) values (83, 'NZL', 'New Zealand');
INSERT INTO lands(id, iso_code, name) values (84, 'OMN', 'Oman');
INSERT INTO lands(id, iso_code, name) values (85, 'NLD', 'Netherlands');
INSERT INTO lands(id, iso_code, name) values (86, 'MNG', 'Mongolia');
INSERT INTO lands(id, iso_code, name) values (87, 'SRB', 'Serbia');
INSERT INTO lands(id, iso_code, name) values (88, 'BGR', 'Bulgaria');
INSERT INTO lands(id, iso_code, name) values (89, 'CZE', 'Czechia');
INSERT INTO lands(id, iso_code, name) values (90, 'URY', 'Uruguay');
INSERT INTO lands(id, iso_code, name) values (91, 'QAT', 'Qatar');
INSERT INTO lands(id, iso_code, name) values (92, 'HND', 'Honduras');
INSERT INTO lands(id, iso_code, name) values (93, 'MOZ', 'Mozambique');
INSERT INTO lands(id, iso_code, name) values (94, 'SEN', 'Senegal');
INSERT INTO lands(id, iso_code, name) values (95, 'IRL', 'Ireland');
INSERT INTO lands(id, iso_code, name) values (96, 'RWA', 'Rwanda');
INSERT INTO lands(id, iso_code, name) values (97, 'LBY', 'Libya');
INSERT INTO lands(id, iso_code, name) values (98, 'GEO', 'Georgia');
INSERT INTO lands(id, iso_code, name) values (99, 'TCD', 'Chad');
INSERT INTO lands(id, iso_code, name) values (100, 'MRT', 'Mauritania');
INSERT INTO lands(id, iso_code, name) values (101, 'TUN', 'Tunisia');
INSERT INTO lands(id, iso_code, name) values (102, 'KGZ', 'Kyrgyzstan');
INSERT INTO lands(id, iso_code, name) values (103, 'TKM', 'Turkmenistan');
INSERT INTO lands(id, iso_code, name) values (104, 'NER', 'Niger');
INSERT INTO lands(id, iso_code, name) values (105, 'NIC', 'Nicaragua');
INSERT INTO lands(id, iso_code, name) values (106, 'LBR', 'Liberia');
INSERT INTO lands(id, iso_code, name) values (107, 'HTI', 'Haiti');
INSERT INTO lands(id, iso_code, name) values (108, 'NPL', 'Nepal');
INSERT INTO lands(id, iso_code, name) values (109, 'SWE', 'Sweden');
INSERT INTO lands(id, iso_code, name) values (110, 'ERI', 'Eritrea');
INSERT INTO lands(id, iso_code, name) values (111, 'SLE', 'Sierra Leone');
INSERT INTO lands(id, iso_code, name) values (112, 'ISR', 'Israel');
INSERT INTO lands(id, iso_code, name) values (113, 'CAF', 'Central African Republic');
INSERT INTO lands(id, iso_code, name) values (114, 'PAN', 'Panama');
INSERT INTO lands(id, iso_code, name) values (115, 'TGO', 'Togo');
INSERT INTO lands(id, iso_code, name) values (116, 'GAB', 'Gabon');
INSERT INTO lands(id, iso_code, name) values (117, 'HRV', 'Croatia');
INSERT INTO lands(id, iso_code, name) values (118, 'TJK', 'Tajikistan');
INSERT INTO lands(id, iso_code, name) values (119, 'BEN', 'Benin');
INSERT INTO lands(id, iso_code, name) values (120, 'LAO', 'Laos');
INSERT INTO lands(id, iso_code, name) values (121, 'LKA', 'Sri Lanka');
INSERT INTO lands(id, iso_code, name) values (122, 'NOR', 'Norway');
INSERT INTO lands(id, iso_code, name) values (123, 'GRC', 'Greece');
INSERT INTO lands(id, iso_code, name) values (124, 'BDI', 'Burundi');
INSERT INTO lands(id, iso_code, name) values (125, 'FIN', 'Finland');
INSERT INTO lands(id, iso_code, name) values (126, 'MKD', 'Macedonia');
INSERT INTO lands(id, iso_code, name) values (127, 'MDA', 'Moldova');
INSERT INTO lands(id, iso_code, name) values (128, 'LVA', 'Latvia');
INSERT INTO lands(id, iso_code, name) values (129, 'DNK', 'Denmark');
INSERT INTO lands(id, iso_code, name) values (130, 'JAM', 'Jamaica');
INSERT INTO lands(id, iso_code, name) values (131, 'LTU', 'Lithuania');
INSERT INTO lands(id, iso_code, name) values (132, 'SLV', 'El Salvador');
INSERT INTO lands(id, iso_code, name) values (133, 'DJI', 'Djibouti');
INSERT INTO lands(id, iso_code, name) values (134, 'PRT', 'Portugal');
INSERT INTO lands(id, iso_code, name) values (135, 'EST', 'Estonia');
INSERT INTO lands(id, iso_code, name) values (136, 'SVK', 'Slovakia');
INSERT INTO lands(id, iso_code, name) values (137, 'ALB', 'Albania');
INSERT INTO lands(id, iso_code, name) values (138, 'LBN', 'Lebanon');
INSERT INTO lands(id, iso_code, name) values (139, 'GNB', 'Guinea-Bissau');
INSERT INTO lands(id, iso_code, name) values (140, 'SSD', 'South Sudan');
INSERT INTO lands(id, iso_code, name) values (141, 'PNG', 'Papua New Guinea');
INSERT INTO lands(id, iso_code, name) values (142, 'LSO', 'Lesotho');
INSERT INTO lands(id, iso_code, name) values (143, 'CYP', 'Cyprus');
INSERT INTO lands(id, iso_code, name) values (144, 'NAM', 'Namibia');
INSERT INTO lands(id, iso_code, name) values (145, 'CRI', 'Costa Rica');
INSERT INTO lands(id, iso_code, name) values (146, 'SVN', 'Slovenia');
INSERT INTO lands(id, iso_code, name) values (147, 'BIH', 'Bosnia And Herzegovina');
INSERT INTO lands(id, iso_code, name) values (148, 'BHS', 'Bahamas, The');
INSERT INTO lands(id, iso_code, name) values (149, 'MTQ', 'Martinique');
INSERT INTO lands(id, iso_code, name) values (150, 'BWA', 'Botswana');
INSERT INTO lands(id, iso_code, name) values (151, 'SUR', 'Suriname');
INSERT INTO lands(id, iso_code, name) values (152, 'TLS', 'Timor-Leste');
INSERT INTO lands(id, iso_code, name) values (153, 'XKS', 'Kosovo');
INSERT INTO lands(id, iso_code, name) values (154, 'GUY', 'Guyana');
INSERT INTO lands(id, iso_code, name) values (155, 'GNQ', 'Equatorial Guinea');
INSERT INTO lands(id, iso_code, name) values (156, 'GIB', 'Gibraltar');
INSERT INTO lands(id, iso_code, name) values (157, 'REU', 'Reunion');
INSERT INTO lands(id, iso_code, name) values (158, 'MDV', 'Maldives');
INSERT INTO lands(id, iso_code, name) values (159, 'MNE', 'Montenegro');
INSERT INTO lands(id, iso_code, name) values (160, 'BHR', 'Bahrain');
INSERT INTO lands(id, iso_code, name) values (161, 'MUS', 'Mauritius');
INSERT INTO lands(id, iso_code, name) values (162, 'CUW', 'Curaçao');
INSERT INTO lands(id, iso_code, name) values (163, 'CHE', 'Switzerland');
INSERT INTO lands(id, iso_code, name) values (164, 'PYF', 'French Polynesia');
INSERT INTO lands(id, iso_code, name) values (165, 'ISL', 'Iceland');
INSERT INTO lands(id, iso_code, name) values (166, 'CPV', 'Cabo Verde');
INSERT INTO lands(id, iso_code, name) values (167, 'LUX', 'Luxembourg');
INSERT INTO lands(id, iso_code, name) values (168, 'BRB', 'Barbados');
INSERT INTO lands(id, iso_code, name) values (169, 'COM', 'Comoros');
INSERT INTO lands(id, iso_code, name) values (170, 'BTN', 'Bhutan');
INSERT INTO lands(id, iso_code, name) values (171, 'SWZ', 'Swaziland');
INSERT INTO lands(id, iso_code, name) values (172, 'NCL', 'New Caledonia');
INSERT INTO lands(id, iso_code, name) values (173, 'SLB', 'Solomon Islands');
INSERT INTO lands(id, iso_code, name) values (174, 'FJI', 'Fiji');
INSERT INTO lands(id, iso_code, name) values (175, 'LCA', 'Saint Lucia');
INSERT INTO lands(id, iso_code, name) values (176, 'GUF', 'French Guiana');
INSERT INTO lands(id, iso_code, name) values (177, 'STP', 'Sao Tome And Principe');
INSERT INTO lands(id, iso_code, name) values (178, 'VUT', 'Vanuatu');
INSERT INTO lands(id, iso_code, name) values (179, 'BMU', 'Bermuda');
INSERT INTO lands(id, iso_code, name) values (180, 'BRN', 'Brunei');
INSERT INTO lands(id, iso_code, name) values (181, 'MCO', 'Monaco');
INSERT INTO lands(id, iso_code, name) values (182, 'TTO', 'Trinidad And Tobago');
INSERT INTO lands(id, iso_code, name) values (183, 'WSM', 'Samoa');
INSERT INTO lands(id, iso_code, name) values (184, 'IMN', 'Isle Of Man');
INSERT INTO lands(id, iso_code, name) values (185, 'ABW', 'Aruba');
INSERT INTO lands(id, iso_code, name) values (186, 'JEY', 'Jersey');
INSERT INTO lands(id, iso_code, name) values (187, 'LIE', 'Liechtenstein');
INSERT INTO lands(id, iso_code, name) values (188, 'GMB', 'Gambia, The');
INSERT INTO lands(id, iso_code, name) values (189, 'MYT', 'Mayotte');
INSERT INTO lands(id, iso_code, name) values (190, 'MHL', 'Marshall Islands');
INSERT INTO lands(id, iso_code, name) values (191, 'KIR', 'Kiribati');
INSERT INTO lands(id, iso_code, name) values (192, 'CYM', 'Cayman Islands');
INSERT INTO lands(id, iso_code, name) values (193, 'SYC', 'Seychelles');
INSERT INTO lands(id, iso_code, name) values (194, 'VCT', 'Saint Vincent And The Grenadines');
INSERT INTO lands(id, iso_code, name) values (195, 'ATG', 'Antigua And Barbuda');
INSERT INTO lands(id, iso_code, name) values (196, 'TON', 'Tonga');
INSERT INTO lands(id, iso_code, name) values (197, 'AND', 'Andorra');
INSERT INTO lands(id, iso_code, name) values (198, 'GRL', 'Greenland');
INSERT INTO lands(id, iso_code, name) values (199, 'BLZ', 'Belize');
INSERT INTO lands(id, iso_code, name) values (200, 'DMA', 'Dominica');
INSERT INTO lands(id, iso_code, name) values (201, 'KNA', 'Saint Kitts And Nevis');
INSERT INTO lands(id, iso_code, name) values (202, 'FRO', 'Faroe Islands');
INSERT INTO lands(id, iso_code, name) values (203, 'ASM', 'American Samoa');
INSERT INTO lands(id, iso_code, name) values (204, 'MLT', 'Malta');
INSERT INTO lands(id, iso_code, name) values (205, 'XGZ', 'Gaza Strip');
INSERT INTO lands(id, iso_code, name) values (206, 'TCA', 'Turks And Caicos Islands');
INSERT INTO lands(id, iso_code, name) values (207, 'FSM', 'Micronesia, Federated States Of');
INSERT INTO lands(id, iso_code, name) values (208, 'TUV', 'Tuvalu');
INSERT INTO lands(id, iso_code, name) values (209, 'COK', 'Cook Islands');
INSERT INTO lands(id, iso_code, name) values (210, 'GRD', 'Grenada');
INSERT INTO lands(id, iso_code, name) values (211, 'SMR', 'San Marino');
INSERT INTO lands(id, iso_code, name) values (212, 'XWB', 'West Bank');
INSERT INTO lands(id, iso_code, name) values (213, 'MNP', 'Northern Mariana Islands');
INSERT INTO lands(id, iso_code, name) values (214, 'GLP', 'Guadeloupe');
INSERT INTO lands(id, iso_code, name) values (215, 'FLK', 'Falkland Islands (Islas Malvinas)');
INSERT INTO lands(id, iso_code, name) values (216, 'VAT', 'Vatican City');
INSERT INTO lands(id, iso_code, name) values (217, 'NIU', 'Niue');
INSERT INTO lands(id, iso_code, name) values (218, 'GUM', 'Guam');
INSERT INTO lands(id, iso_code, name) values (219, 'SHN', 'Saint Helena, Ascension, And Tristan Da Cunha');
INSERT INTO lands(id, iso_code, name) values (220, 'MAF', 'Saint Martin');
INSERT INTO lands(id, iso_code, name) values (221, 'SXM', 'Sint Maarten');
INSERT INTO lands(id, iso_code, name) values (222, 'VGB', 'Virgin Islands, British');
INSERT INTO lands(id, iso_code, name) values (223, 'BLM', 'Saint Barthelemy');
INSERT INTO lands(id, iso_code, name) values (224, 'SPM', 'Saint Pierre And Miquelon');
INSERT INTO lands(id, iso_code, name) values (225, 'AIA', 'Anguilla');
INSERT INTO lands(id, iso_code, name) values (226, 'WLF', 'Wallis And Futuna');
INSERT INTO lands(id, iso_code, name) values (227, 'NFK', 'Norfolk Island');
INSERT INTO lands(id, iso_code, name) values (228, 'PLW', 'Palau');
INSERT INTO lands(id, iso_code, name) values (229, 'ESH', 'Western Sahara');
INSERT INTO lands(id, iso_code, name) values (230, 'XSV', 'Svalbard');
INSERT INTO lands(id, iso_code, name) values (231, 'PCN', 'Pitcairn Islands');
INSERT INTO lands(id, iso_code, name) values (232, 'CXR', 'Christmas Island');
INSERT INTO lands(id, iso_code, name) values (233, 'MAC', 'Macau');
INSERT INTO lands(id, iso_code, name) values (234, 'PRI', 'Puerto Rico');
INSERT INTO lands(id, iso_code, name) values (235, 'SGS', 'South Georgia And South Sandwich Islands');
